### ISSUE TITLE
RC: Build `nitro` `node-server` exception with initial request and headers

### ISSUE THREAD

**Issue by kevinehosford** [tannerlinsley/react-location#5263]
### Which project does this relate to?

Start

### Describe the bug

Hi! I tried building using the nitro compatibility plugin and using `node-server` to mimic the setup I was using before upgrading to the RC and am seeing:
- `request` only has a relative url and in Start this throws an exception with `new URL(req.url).origin`
- `request.header.get` is undefined, it looks like this is the node incoming request (also unhandled)

```
DEBUG: Request object type: object
DEBUG: Request constructor: IncomingMessage
DEBUG: Request headers type: object
DEBUG: Headers.get exists: undefined
TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    ... 8 lines matching cause stack trace ...
    at Object.handler (file:///Users/khosford/source/start-request/request-bug/.output/server/index.mjs:1558:31) {
  cause: TypeError: Invalid URL
      at new URL (node:internal/url:818:25)
      at startRequestResolver (file:///Users/khosford/source/start-request/request-bug/.output/server/chunks/virtual/entry.mjs:1059:17)
      at file:///Users/khosford/source/start-request/request-bug/.output/server/chunks/virtual/entry.mjs:646:13
      at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
      at Object.fetch (file:///Users/khosford/source/start-request/request-bug/.output/server/chunks/virtual/entry.mjs:644:35)
      at fetch (file:///Users/khosford/source/start-request/request-bug/.output/server/chunks/virtual/entry.mjs:1371:21)
      at Object.handler (file:///Users/khosford/source/start-request/request-bug/.output/server/chunks/virtual/entry.mjs:378:20)
      at Object.handler (file:///Users/khosford/source/start-request/request-bug/.output/server/index.mjs:1487:24)
      at Object.handler (file:///Users/khosford/source/start-request/request-bug/.output/server/index.mjs:1797:34)
      at Object.handler (file:///Users/khosford/source/start-request/request-bug/.output/server/index.mjs:1558:31) {
    code: 'ERR_INVALID_URL',
    input: '/.well-known/appspecific/com.chrome.devtools.json'
  },
  status: 500,
  statusText: undefined,
  headers: undefined,
  data: undefined,
  body: undefined,
  unhandled: true
}
```

### Your Example Website or App

https://github.com/kevinehosford/start-incoming-request

### Steps to Reproduce the Bug or Issue

1. git clone https://github.com/kevinehosford/start-incoming-request
2. (p)npm i, build, start
3. visit localhost:3000 and see 

```json
{"status":500,"unhandled":true,"message":"HTTPError"}
```

### Expected behavior

I expected the page would load and no exception thrown

### Platform

```
    "@tanstack/nitro-v2-vite-plugin": "^1.132.0",
    "@tanstack/react-router": "^1.132.0",
    "@tanstack/react-router-ssr-query": "^1.131.7",
    "@tanstack/react-start": "^1.132.0",
    "@tanstack/router-plugin": "^1.132.0",
    "nitropack": "^2.12.6",
    "vite": "^7.1.7",
```

### Additional context

The upgrade was smooth! Just wondering what I can do about this. Thanks!

**Comment by schiller-manuel** [comment]
i cannot reproduce this when installing with pnpm.

```
DEBUG: Request object type: object
DEBUG: Request constructor: Request
DEBUG: Request headers type: object
DEBUG: Headers.get exists: function
```

however, i can reproduce when installing with npm.

the underlying issue is that nitro v2 uses h3 v1 while start internally uses h3 v2.
npm seems to not be able to correctly install two versions of the same dependency while pnpm is able to.

i think that cannot be solved for npm unfortunately.

**Comment by nyomansunima** [comment]
When fresh project created also failing into error. I've tried to build new project using "create-start-app". This happen because "The .output/server/index.mjs" doesn't exist. 

It's works fine when in dev mode, but when tried to build and start it, it's keep failing.

**Comment by medihack** [comment]
I can confirm this problem as well. With `@tanstack/nitro-v2-vite-plugin 1.132.0` (`@tanstack/react-start 1.132.19`, `@tanstack/react-router 1.132.19`), I end up with the same error on Vercel when using `npm`. So, I switched to `pnpm` as @schiller-manuel suggested, and the problem is gone (I had always been looking for a hard reason to switch to `pnpm` anyway 😉).

**Comment by nyomansunima** [comment]
Upgrade the packages

**Comment by medihack** [comment]
> Upgrade the packages

@nyomansunima, what do you mean by that? It seems I am already on up-to-date packages (`@tanstack/nitro-v2-vite-plugin 1.132.0`, `@tanstack/react-start 1.132.19`, `@tanstack/react-router 1.132.19`).

**Comment by kevinehosford** [comment]
confirmed switching to `pnpm` fixed it for our project. great find, @schiller-manuel.

for others, who might encounter this - i tried tweaking overrides to see if `npm` would cooperate but that didn't work out.

**Comment by schiller-manuel** [comment]
fixed this in https://github.com/TanStack/router/releases/tag/v1.132.21

now works with npm as well

**Comment by mbauchet** [comment]
I’m still encountering the same issue with the latest versions of Router (1.132.47) and Start (1.132.48).
