### ISSUE TITLE
Bug in search params encoding in navigate hook

### ISSUE THREAD

**Issue by chidimo** [tannerlinsley/react-location#75]
**Describe the bug**
The first time I used `react-location` was version `3.1.0-next.4` with the `ReactLocationProvider` component. The first thing that got me hooked was the way I could update my search params with the `useNavigate` hook and retrieve them with the `useSearch` hook. I could set and retrieve search param without worrying about encoding and decoding.
I upgraded to `3.1.0` a few days ago and found that the `useNavigate` hook behaviour has changed. Now when I try to set an array search params it is always saved as a string.
The current docs say that `JSON.parse` and `JSON.stringify` are used by default to ensure the search params can contain complex objects, but that is currently not the case.

I also tried to provide parseSearch and stringifySearch from `react-location-jsurl` to `ReactLocation` but when I try to update my search params it ends up lumping all of the URLs together leading to a 404 page. It doesn't include the `?` to differentiate the search params from the root location.

**To Reproduce**

I created a codesandbox to demonstrate this.
<https://codesandbox.io/s/react-location-search-uv1fz>

When you click on next you should observe that the JSON object has a string for the `after` param even though I set it to an array. The expected result (what we have in `3.1.0-next.4`) is shown above the actual result.

**Additional context**

I have been trying for the past two days to decide if this is a bug or an expected behaviour. The docs are not clear if this is the new behaviour.
In case this is the expected behaviour I'd be more than happy to learn how best to proceed and to help update the docs.

**Comment by tannerlinsley** [comment]
Sounds like a bug. The behavior changed to *not* include the JSURL compression by default, so that's expected, but the fact that it's leaving out the `?` seems fishy. I'll look into it asap.

**Comment by tannerlinsley** [comment]
Fixed with 66fab0a3ac8368451cb6bba41f6c5380aa134f29

**Comment by chidimo** [comment]
I installed version 3.1.10 and the error is still there.

I tried to install the commit with the fix with `yarn add https://github.com/tannerlinsley/react-location#66fab0a` but it throws the below error `error Can't add undefined: invalid package version undefined.`. I did some search and found that the error might be related to the fact that no version is specified in the `package.json` file.

I'd really appreciate help with this.
Thank you
